#!/usr/bin/env bash
# REECE specific settings

function auth-non-prod-a() {
	kubectl config set-cluster non-prod-a --server=https://10.99.10.225:6443 --certificate-authority=/tmp/nonprod-ca.crt --embed-certs=true
	kubectl config set-credentials azure-user-config --auth-provider=azure --auth-provider-arg=apiserver-id=1f4e75bb-714c-4a10-985b-14ff3a1034dc --auth-provider-arg=client-id=449d806e-d055-485b-b453-a7b3b1425935 --auth-provider-arg=tenant-id=fa5a8b25-2ea1-4eba-80e2-a0a945e1dc36
	kubectl config set-context nonprod-a --cluster=non-prod-a --user=azure-user-config
	kubectl config use-context nonprod-a
}

function auth-non-prod-b() {
	kubectl config set-cluster non-prod-b --server=https://apiserver.b.test.reecenet.org:6443 --certificate-authority=/tmp/nonprod-ca.crt --embed-certs=true
	kubectl config set-credentials azure-user-config --auth-provider=azure --auth-provider-arg=apiserver-id=1f4e75bb-714c-4a10-985b-14ff3a1034dc --auth-provider-arg=client-id=449d806e-d055-485b-b453-a7b3b1425935 --auth-provider-arg=tenant-id=fa5a8b25-2ea1-4eba-80e2-a0a945e1dc36
	kubectl config set-context nonprod-b --cluster=non-prod-b --user=azure-user-config
	kubectl config use-context nonprod-b
}

function auth-prod() {
	kubectl config set-cluster prod-a --server=https://10.99.10.151:6443 --certificate-authority=/tmp/prod-ca.crt --embed-certs=true
	kubectl config set-credentials azure-user-config --auth-provider=azure --auth-provider-arg=apiserver-id=1f4e75bb-714c-4a10-985b-14ff3a1034dc --auth-provider-arg=client-id=449d806e-d055-485b-b453-a7b3b1425935 --auth-provider-arg=tenant-id=fa5a8b25-2ea1-4eba-80e2-a0a945e1dc36
	kubectl config set-context prod-a --cluster=prod-a --user=azure-user-config
	kubectl config use-context prod-a
}

function auth-dmz-non-prod() {
	kubectl config set-cluster dmznon-prod --server=https://172.24.21.226:6443 --certificate-authority=/tmp/nonprod-ca.crt --embed-certs=true
	kubectl config set-credentials azure-user-config --auth-provider=azure --auth-provider-arg=apiserver-id=1f4e75bb-714c-4a10-985b-14ff3a1034dc --auth-provider-arg=client-id=449d806e-d055-485b-b453-a7b3b1425935 --auth-provider-arg=tenant-id=fa5a8b25-2ea1-4eba-80e2-a0a945e1dc36
	kubectl config set-context dmznonprod --cluster=dmznon-prod --user=azure-user-config
	kubectl config use-context dmznonprod
}


function auth-dmz-prod() {
	kubectl config set-cluster dmzprod --server=https://172.24.17.226:6443 --certificate-authority=/tmp/prod-ca.crt --embed-certs=true
	kubectl config set-credentials azure-user-config --auth-provider=azure --auth-provider-arg=apiserver-id=1f4e75bb-714c-4a10-985b-14ff3a1034dc --auth-provider-arg=client-id=449d806e-d055-485b-b453-a7b3b1425935 --auth-provider-arg=tenant-id=fa5a8b25-2ea1-4eba-80e2-a0a945e1dc36
	kubectl config set-context dmzprod --cluster=dmzprod --user=azure-user-config --namespace=kube-system
	kubectl config use-context dmzprod
}
